homeservers:
  vars:
    ansible_become_user: root
    ansible_become: true 
  hosts:
    server1:
      ansible_host: "{{ server1_ip }}"
      ansible_user: "{{ server1_user }}"
      ansible_ssh_private_key_file: "{{ server1_key }}"
      ansible_sudo_pass: "{{ server1_sudo_pass }}"
