- hosts: all
  remote_user: root
  vars:
    favcolor: blue
  vars_files:
    - external-vars.yml

- name: My first play
  hosts: homeservers
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello servers!
